### ISSUE TITLE
Không rớt đồ xanh khi đánh quái ?

### ISSUE THREAD

**Issue by phongdatgl** [vnshares/jx-dev#32]
Cho mình hỏi có phải script lỗi phần rớt đồ khi đánh quái không mà đánh quái rớt toàn đồ trắng. 
Mình đã xem lại file dropitem thấy gọi hàm **DropNpcItem**, có param là _pluck_ -> _điểm may mắn của nhân vật_. Mình đã thử add lên 100, 1000 vẫn không ra được đồ xanh. Không biết có phải lỗi ko nhỉ, ae nào gặp trường hợp này chưa ?

**Comment by rinodung** [comment]
Bạn xem thêm phần rớt item ở các map 0x-9x nhé.
